USE [master]
GO

/****** Object:  Database [COFFESHOP]    Script Date: 9/29/2019 1:41:49 AM ******/
CREATE DATABASE [COFFESHOP]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'COFFESHOP', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\COFFESHOP.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'COFFESHOP_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.MSSQLSERVER\MSSQL\DATA\COFFESHOP_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [COFFESHOP] SET COMPATIBILITY_LEVEL = 140
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [COFFESHOP].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [COFFESHOP] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [COFFESHOP] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [COFFESHOP] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [COFFESHOP] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [COFFESHOP] SET ARITHABORT OFF 
GO

ALTER DATABASE [COFFESHOP] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [COFFESHOP] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [COFFESHOP] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [COFFESHOP] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [COFFESHOP] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [COFFESHOP] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [COFFESHOP] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [COFFESHOP] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [COFFESHOP] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [COFFESHOP] SET  ENABLE_BROKER 
GO

ALTER DATABASE [COFFESHOP] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [COFFESHOP] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [COFFESHOP] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [COFFESHOP] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [COFFESHOP] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [COFFESHOP] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [COFFESHOP] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [COFFESHOP] SET RECOVERY FULL 
GO

ALTER DATABASE [COFFESHOP] SET  MULTI_USER 
GO

ALTER DATABASE [COFFESHOP] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [COFFESHOP] SET DB_CHAINING OFF 
GO

ALTER DATABASE [COFFESHOP] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [COFFESHOP] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [COFFESHOP] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [COFFESHOP] SET QUERY_STORE = OFF
GO

ALTER DATABASE [COFFESHOP] SET  READ_WRITE 
GO

